// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });



import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
 
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
   
   
    url: "sqlserver://192.168.0.200:1433;database=WhatsAppMarketing;user=admin;password=admin@pns123;trustServerCertificate=true;integratedSecurity=false;encrypt=true",
  },
});



